In [7]:
import numpy as np
A = 12500
B = 11800
C = 15900
D = 25300

25300

In [23]:
PRECIO = np.matrix([[A,A,A,A],[B,B,B,B],[C,C,C,C],[D,D,D,D]])
PRECIO

matrix([[12500, 12500, 12500, 12500],
        [11800, 11800, 11800, 11800],
        [15900, 15900, 15900, 15900],
        [25300, 25300, 25300, 25300]])

In [ ]:
E = 

In [24]:
CANTIDAD = np.matrix([[10,8,12,0],[5,6,8,0],[8,4,14,0],[3,2,6,0]])
CANTIDAD

matrix([[10,  8, 12,  0],
        [ 5,  6,  8,  0],
        [ 8,  4, 14,  0],
        [ 3,  2,  6,  0]])

In [49]:
TOTAL1 = np.multiply(PRECIO,CANTIDAD)
TOTAL1

matrix([[125000, 100000, 150000,      0],
        [ 59000,  70800,  94400,      0],
        [127200,  63600, 222600,      0],
        [ 75900,  50600, 151800,      0]])

In [63]:
ABRILA=(np.multiply(TOTAL1[0,2],0.05))+(TOTAL1[0,2])
ABRILA

157500.0

In [64]:
ABRILB=(np.multiply(TOTAL1[1,2],0.05))+(TOTAL1[1,2])
ABRILB

99120.0

In [65]:
ABRILC=(np.multiply(TOTAL1[2,2],0.05))+(TOTAL1[2,2])
ABRILC

233730.0

In [66]:
ABRILD=(np.multiply(TOTAL1[3,2],0.05))+(TOTAL1[3,2])
ABRILD

159390.0

In [91]:
CANTIDAD1 = np.matrix([[10,8,12,ABRILA],[5,6,8,ABRILB],[8,4,14,ABRILC],[3,2,6,ABRILD]])
CANTIDAD1

matrix([[1.0000e+01, 8.0000e+00, 1.2000e+01, 1.5750e+05],
        [5.0000e+00, 6.0000e+00, 8.0000e+00, 9.9120e+04],
        [8.0000e+00, 4.0000e+00, 1.4000e+01, 2.3373e+05],
        [3.0000e+00, 2.0000e+00, 6.0000e+00, 1.5939e+05]])

In [92]:
TOTAL2 = np.multiply(PRECIO,CANTIDAD1)
TOTAL2

matrix([[1.250000e+05, 1.000000e+05, 1.500000e+05, 1.968750e+09],
        [5.900000e+04, 7.080000e+04, 9.440000e+04, 1.169616e+09],
        [1.272000e+05, 6.360000e+04, 2.226000e+05, 3.716307e+09],
        [7.590000e+04, 5.060000e+04, 1.518000e+05, 4.032567e+09]])

In [93]:
ENERO = np.sum(TOTAL2[0:,0])
print("LO RECAUDADO EN EL MES DE ENERO ES: ",ENERO)

LO RECAUDADO EN EL MES DE ENERO ES:  387100.0


In [94]:
FEBRERO = np.sum(TOTAL2[0:,1])
print("LO RECAUDADO EN EL MES DE FEBRERO ES: ",FEBRERO)

LO RECAUDADO EN EL MES DE FEBRERO ES:  285000.0


In [95]:
MARZO = np.sum(TOTAL2[0:,2])
print("LO RECAUDADO EN EL MES DE MARZO ES: ",MARZO)

LO RECAUDADO EN EL MES DE MARZO ES:  618800.0


In [96]:
ABRIL = np.sum(TOTAL2[0:,3])
print("LO RECAUDADO EN EL MES DE ABRIL ES: ",ABRIL)

LO RECAUDADO EN EL MES DE ABRIL ES:  10887240000.0


In [97]:
TOTAL3 = np.sum(TOTAL2)
TOTAL3

10888530900.0