In [7]:
import numpy as np
A = 12500
B = 11800
C = 15900
D = 25300

In [8]:
PRECIO = np.matrix([[A,A,A,A],[B,B,B,B],[C,C,C,C],[D,D,D,D]])
PRECIO

matrix([[12500, 12500, 12500, 12500],
        [11800, 11800, 11800, 11800],
        [15900, 15900, 15900, 15900],
        [25300, 25300, 25300, 25300]])

In [9]:
CANTIDAD = np.matrix([[10,8,12,0],[5,6,8,0],[8,4,14,0],[3,2,6,0]])
CANTIDAD

matrix([[10,  8, 12,  0],
        [ 5,  6,  8,  0],
        [ 8,  4, 14,  0],
        [ 3,  2,  6,  0]])

In [10]:
TOTAL1 = np.multiply(PRECIO,CANTIDAD)
TOTAL1

matrix([[125000, 100000, 150000,      0],
        [ 59000,  70800,  94400,      0],
        [127200,  63600, 222600,      0],
        [ 75900,  50600, 151800,      0]])

In [11]:
ABRILA=(np.multiply(TOTAL1[0,2],0.05))+(TOTAL1[0,2])
ABRILA

157500.0

In [12]:
ABRILB=(np.multiply(TOTAL1[1,2],0.05))+(TOTAL1[1,2])
ABRILB

99120.0

In [13]:
ABRILC=(np.multiply(TOTAL1[2,2],0.05))+(TOTAL1[2,2])
ABRILC

233730.0

In [14]:
ABRILD=(np.multiply(TOTAL1[3,2],0.05))+(TOTAL1[3,2])
ABRILD

159390.0

In [22]:
CANTIDAD1 = np.matrix([[125000,100000,150000,ABRILA],[59000,70800,94400,ABRILB],[127200,63600,222600,ABRILC],[75900,50600,151800,ABRILD]])
CANTIDAD1.astype(int)

matrix([[125000, 100000, 150000, 157500],
        [ 59000,  70800,  94400,  99120],
        [127200,  63600, 222600, 233730],
        [ 75900,  50600, 151800, 159390]])

In [24]:
ENERO = np.sum(CANTIDAD1[0:,0])
print("LO RECAUDADO EN EL MES DE ENERO ES: ",ENERO)

LO RECAUDADO EN EL MES DE ENERO ES:  387100.0


In [25]:
FEBRERO = np.sum(CANTIDAD1[0:,1])
print("LO RECAUDADO EN EL MES DE FEBRERO ES: ",FEBRERO)

LO RECAUDADO EN EL MES DE FEBRERO ES:  285000.0


In [26]:
MARZO = np.sum(CANTIDAD1[0:,2])
print("LO RECAUDADO EN EL MES DE MARZO ES: ",MARZO)

LO RECAUDADO EN EL MES DE MARZO ES:  618800.0


In [27]:
ABRIL = np.sum(CANTIDAD1[0:,3])
print("LO RECAUDADO EN EL MES DE ABRIL ES: ",ABRIL)

LO RECAUDADO EN EL MES DE ABRIL ES:  649740.0


In [28]:
TOTAL3 = ENERO+FEBRERO+MARZO+ABRIL
TOTAL3

1940640.0